

CURRENT_DIR=$(pwd)

CATALYST_COMPILER_DIR="/workspaces/compilers/MQSS-Catalyst-Compiler"
DIALECTS_BUILD_DIR=${CURRENT_DIR}"/build"
LLVM_BUILD_DIR= "${CATALYST_COMPILER_DIR}/llvm-project/build"

BUILD_TYPE="Debug"

source ${CATALYST_COMPILER_DIR}/catalyst-venv/bin/activate                      # Edit in the future

PYTHON="${PYTHON:-$(which python3)}"
C_COMPILER="${C_COMPILER:-$(which clang)}"
CXX_COMPILER="${CXX_COMPILER:-$(which clang++)}"
COMPILER_LAUNCHER="${COMPILER_LAUNCHER:-$(which ccache)}"

ifeq ($(shell uname), Darwin)
DEFAULT_ENABLE_LLD= OFF
SYMBOL_VISIBILITY := default
else
DEFAULT_ENABLE_LLD := ON
SYMBOL_VISIBILITY := default
endif

ENABLE_LLD= $(DEFAULT_ENABLE_LLD)
ENABLE_ZLIB=ON
ENABLE_ZSTD=OFF
ENABLE_ASAN=OFF
STRICT_WARNINGS=ON

ifeq ($(ENABLE_ASAN), ON)
USE_SANITIZER_NAMES="Address"
USE_SANITIZER_FLAGS="-fsanitize=address"
else
USE_SANITIZER_NAMES=""
USE_SANITIZER_FLAGS=""
endif

LLVM_PROJECTS= mlir
LLVM_TARGETS= check-mlir llvm-symbolizer


# Command to build the required LLVM version (21.0.0)
# cmake -G Ninja -S llvm-project/llvm -B $(LLVM_BUILD_DIR) \
# 	-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
# 	-DLLVM_BUILD_EXAMPLES=OFF \
# 	-DLLVM_TARGETS_TO_BUILD="host" \
# 	-DLLVM_ENABLE_PROJECTS="$(LLVM_PROJECTS)" \
# 	-DLLVM_ENABLE_ASSERTIONS=ON \
# 	-DMLIR_ENABLE_BINDINGS_PYTHON=ON \
# 	-DPython_EXECUTABLE=$(PYTHON) \
# 	-DPython3_EXECUTABLE=$(PYTHON) \
# 	-DPython3_NumPy_INCLUDE_DIRS=$$($(PYTHON) -c "import numpy as np; print(np.get_include())") \
# 	-DCMAKE_C_COMPILER=$(C_COMPILER) \
# 	-DCMAKE_CXX_COMPILER=$(CXX_COMPILER) \
# 	-DCMAKE_C_COMPILER_LAUNCHER=$(COMPILER_LAUNCHER) \
# 	-DCMAKE_CXX_COMPILER_LAUNCHER=$(COMPILER_LAUNCHER) \
# 	-DLLVM_USE_SANITIZER=$(USE_SANITIZER_NAMES) \
# 	-DLLVM_ENABLE_LLD=$(ENABLE_LLD) \
# 	-DLLVM_ENABLE_ZLIB=$(ENABLE_ZLIB) \
# 	-DLLVM_ENABLE_ZSTD=$(ENABLE_ZSTD) \
# 	-DCMAKE_CXX_VISIBILITY_PRESET=$(SYMBOL_VISIBILITY)


cmake -G Ninja -S . -B $(DIALECTS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
		-DLLVM_ENABLE_ASSERTIONS=ON \
		-DQUANTUM_ENABLE_BINDINGS_PYTHON=ON \
		-DPython3_EXECUTABLE=$(PYTHON) \
		-DPython3_NumPy_INCLUDE_DIRS=$(shell $(PYTHON) -c "import numpy as np; print(np.get_include())") \
		# -DEnzyme_DIR=$(ENZYME_BUILD_DIR) \
		# -DENZYME_SRC_DIR=$(MK_DIR)/Enzyme \
		-DMLIR_DIR=$(LLVM_BUILD_DIR)/lib/cmake/mlir \
		# -DMHLO_DIR=$(MHLO_BUILD_DIR)/lib/cmake/mlir-hlo \
		# -DMHLO_BINARY_DIR=$(MHLO_BUILD_DIR)/bin \
		# -DRUNTIME_LIB_DIR=$(RT_BUILD_DIR)/lib \
		-DMLIR_LIB_DIR=$(LLVM_BUILD_DIR)/lib \
		-DCMAKE_C_COMPILER=$(C_COMPILER) \
		-DCMAKE_CXX_COMPILER=$(CXX_COMPILER) \
		-DCMAKE_C_COMPILER_LAUNCHER=$(COMPILER_LAUNCHER) \
		-DCMAKE_CXX_COMPILER_LAUNCHER=$(COMPILER_LAUNCHER) \
		-DLLVM_USE_SANITIZER=$(USE_SANITIZER_NAMES) \
		-DLLVM_ENABLE_LLD=$(ENABLE_LLD) \
		-DLLVM_ENABLE_ZLIB=$(ENABLE_ZLIB) \
		-DLLVM_ENABLE_ZSTD=$(ENABLE_ZSTD) \
		-DCATALYST_ENABLE_WARNINGS=$(STRICT_WARNINGS)