#!/usr/bin/env bash

# Simple driver for selecting the correct optimizer

############# Pretty-print variables#################


msg() {
  printf '%s\n' "$1"
}

blank() {
  printf '\n'
}

section() {
  blank
  printf '====== %s ======\n' "$1"
  blank
}

info() {
  printf '[INFO] %s\n' "$1"
}

ok() {
  printf '[OK]   %s\n' "$1"
}

warn() {
  printf '[WARN] %s\n' "$1"
}

step() {
  printf '  -> %s\n' "$1"
}

usage() {
  cat <<'EOF'
Usage:
  mqss-cc <input.{cpp|py}> [options] --passes=<pass-name>=mode=<mode>

options:
  Common:
    --out-dir DIR

  Python-only:
    --function NAME
    --stage NAME
    --resolver PATH

  Example Usage:
  1. For cudaq-quake
      mqss-cc test.cpp --out-dir output/ --passes=CommonGateCancellationPass=mode=CancelGate

  2. For catalyst-quantum
      mqss-cc test.py --function circuit --stage QuantumCompilationStage --out-dir output/ --passes=CommonGateCancellationPass=mode=CancelGate
EOF
}


PASSES=""
OTHER_ARGS=()

# MQSS_INSTALL_DIR="/workspaces/mqss-install"
# # The following paths should be set on the command-line

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
export CUDA_QUAKE="/workspaces/MQSS-Passes-Suite/_deps/mqss-cudaq/cudaq/bin/cudaq-quake"

for cmd in mqss-cudaq-opt mqss-catalyst-opt mqss-cc; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "$cmd not found"
    fi
done


if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

INPUT_FILE="$1"
shift

if [[ ! -f "${INPUT_FILE}" ]]; then
  echo "Error: input file not found: ${INPUT_FILE}" >&2
  exit 1
fi

EXT="${INPUT_FILE##*.}"
FUNCTION_NAME=""
RESOLVER="${SCRIPT_DIR}/resolve_python_input.py"
STAGE="HLOLoweringStage"
OUT_DIR=""
TOOL_ARGS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-dir)
      OUT_DIR="$2"
      shift 2
      ;;

    --function)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --function is only valid for Python input." >&2
        exit 1
      fi
      FUNCTION_NAME="$2"
      shift 2
      ;;

    --stage)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --stage is only valid for Python input." >&2
        exit 1
      fi
      STAGE="$2"
      shift 2
      ;;

    --resolver)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --resolver is only valid for Python input." >&2
        exit 1
      fi
      RESOLVER="$2"
      shift 2
      ;;

      --passes=*)
        PASSES="${1#--passes=}"
        break
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# TODO: Following code needs improvement
if [[ -z "$INPUT_FILE" ]]; then
echo "No valid input file found!"
exit 1
fi

# TODO: Code to display helper options
# for arg in "${OTHER_ARGS[@]}"; do
#     if [[ "$arg" == -h ]]; then
#         {
#             "${MQSS_CUDAQ_OPT}" -h
#             "${MQSS_CATALYST_OPT}" -h
#         } | awk '!seen[$0]++'
#     fi
# done

# Split passes at commas
PASS_ARGS=()
IFS=',' read -ra PASS_LIST <<< "$PASSES"

for p in "${PASS_LIST[@]}"; do
    PASS_ARGS+=(--"$p")
done


# Dispatch to correct optimizer
if [[ "${EXT}" == "cpp" ]]; then
    blank
    info "Converting the input to MLIR and applying specified optimization passes.."
    filename=$(basename "$INPUT_FILE")
    GENERATED_MLIR="${filename%.*}.qke"
    
    if [[ "${OUT_DIR}" != "" ]]; then
      "${CUDA_QUAKE}" "${INPUT_FILE}" -o "${OUT_DIR}/${GENERATED_MLIR}"
      mqss-cudaq-opt "${OUT_DIR}/${GENERATED_MLIR}" "${PASS_ARGS[@]}" -o "${OUT_DIR}/${GENERATED_MLIR}"
    else
      "${CUDA_QUAKE}" "${INPUT_FILE}" | mqss-cudaq-opt "${PASS_ARGS[@]}"
    fi
    # TODO: Further convert to QIR?

elif [[ "${EXT}" == "py" ]]; then
    blank
    msg "Python job details..."
    info "Function name: ${FUNCTION_NAME}"
    info "Stage: ${STAGE}"
    info "Resolver file: ${RESOLVER}"
    info "Passes: ${PASSES}"
    info "Out Dir: ${OUT_DIR}"

    if python3.11 -c "import catalyst"; then
     info "Catalyst python package found in current env"
    else
      warn "Catalyst python package not found"
      warn "Please enable the python virtual environment: source  MQSS-Passes-Suite/build/_deps/venv/bin/activate"
      exit 1
    fi

    COMMAND=""
    if [[ "${OUT_DIR}" != "" ]]; then
      COMMAND="$(
      python3.11 "${RESOLVER}" \
        --input "${INPUT_FILE}" \
        --function "${FUNCTION_NAME}" \
        --stage "${STAGE}" \
        --out-dir "${OUT_DIR}"
      )"
      MLIR_FILE="${OUT_DIR}/${FUNCTION_NAME}-${STAGE}.mlir"
      if [[ -e "${MLIR_FILE}" ]]; then
        info "MLIR Extracted: ${MLIR_FILE}"
      else
        warn "MLIR dialect could not be extracted"
        exit 1
      fi
      mqss-catalyst-opt "${MLIR_FILE}" "${PASS_ARGS[@]}" -o "${MLIR_FILE}"

    else
      python3.11 "${RESOLVER}" \
        --input "${INPUT_FILE}" \
        --function "${FUNCTION_NAME}" \
        --stage "${STAGE}" |  mqss-catalyst-opt "${PASS_ARGS[@]}"
    fi

    
    # TODO: Further convert to QIR?
else
    warn "Unknown input type: $INPUT_FILE"
    exit 1
fi