#!/usr/bin/env bash

# Simple driver for selecting the correct optimizer

############# Pretty-print variables#################


msg() {
  printf '%s\n' "$1"
}

blank() {
  printf '\n'
}

section() {
  blank
  printf '====== %s ======\n' "$1"
  blank
}

info() {
  printf '[INFO] %s\n' "$1"
}

ok() {
  printf '[OK]   %s\n' "$1"
}

warn() {
  printf '[WARN] %s\n' "$1"
}

step() {
  printf '  -> %s\n' "$1"
}

usage() {
  cat <<'EOF'
Usage:
  mqss-cc <input.{cpp|py}> [options] --passes=<pass-name>=mode=<mode>

options:
  Common:
    --out-dir <Path/to/DIR>
    --emit-qir

  Python-only:
    --function <NAME>

Compiler passes to run
    Passes:
      CommonCommutePass                              -   This pass searches commutes gates that match a specific pattern.
        --mode=<string>                                - Select Pattern to Commute: CX-RX, RX-CX, CX-X, X-CX, CX-Z, Z-CX.
      CommonDecompositionPass                        -   Perform Gate Decomposition, {Cx} -> HCzH or {Cz} -> HCxH or ReverseCx. 
        --mode=<string>                                - Select PassMode CxToHCzH ,CzToHCxH or ReverseCx.
      CommonGateCancellationPass                     -   Performs cancellation of Gates following a specific pattern
        --mode=<string>                                - Select Pattern to Cancel: CancelGate or CancelNullRotation.
      CommonMappingPass                              -   A Dialect agnostic mapping pass
        --input=<string>                               - Path to json input.
      CommonNormalizeArgAnglePass                    -   Normalize Arg angle of RX, RY, RZ gates. 
      CommonReductionPass                            -   Perform Circuit Reduction, {HZH} -> X, {HXH} -> Z, {SAdjZ} -> S or {SZ} -> SAdj. 
        --mode=<string>                                - Select PassMode HXHToZ , HZHToX, SAdjZToS or SZToSAdj.
      CommonSwitchPass                               -   Commute and Switch Gates.
        --mode=<string>                                - Select Pattern to Switch: XYZHtoHXYZ or HXYZtoXYZH.
      canonicalize                                   -   Canonicalize operations
        --disable-patterns=<string>                    - Labels of patterns that should be filtered out during application
        --enable-patterns=<string>                     - Labels of patterns that should be used during application, all other patterns are filtered out
        --max-iterations=<long>                        - Max. iterations between applying patterns / simplifying regions
        --max-num-rewrites=<long>                      - Max. number of pattern rewrites within an iteration
        --region-simplify                              - Perform control flow optimizations to the region tree
        --test-convergence                             - Test only: Fail pass on non-convergence to detect cyclic pattern
        --top-down                                     - Seed the worklist in general top-down order
      cse                                            -   Eliminate common sub-expressions
      print-quake-gates-pass                         -   Example pass that traverses a given mlir module, print its gates and a description of the operands of each gate
      print-catalyst-gates-pass                      -   Example pass that traverses a given mlir module, print its gates and a description of the operands of each gate

Example Usage:
  1. For cudaq-quake
      mqss-cc test.cpp --emit-qir --out-dir output/ --passes=CommonGateCancellationPass=mode=CancelGate

  2. For catalyst-quantum
      mqss-cc test.py --function circuit --stage QuantumCompilationStage --out-dir output/ --passes=CommonGateCancellationPass=mode=CancelGate
EOF
}

while getopts "h" opt; do
  case "$opt" in
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done

PASSES=""
OTHER_ARGS=()

# MQSS_INSTALL_DIR="/workspaces/mqss-install"
# # The following paths should be set on the command-line

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# export CUDA_QUAKE="/workspaces/MQSS-Passes-Suite/_deps/mqss-cudaq/cudaq/bin/cudaq-quake"

for cmd in mqss-cudaq-opt mqss-catalyst-opt mqss-cc; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "$cmd not found"
    fi
done


if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

INPUT_FILE="$1"
shift

if [[ ! -f "${INPUT_FILE}" ]]; then
  echo "Error: input file not found: ${INPUT_FILE}" >&2
  exit 1
fi

EXT="${INPUT_FILE##*.}"
FUNCTION_NAME=""
RESOLVER="${SCRIPT_DIR}/resolve_python_input.py"
STAGE="HLOLoweringStage"
OUT_DIR=""
TOOL_ARGS=()

EMIT_QIR=OFF
DEBUG_ONLY=""
# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-dir)
      OUT_DIR="$2"
      shift 2
      ;;
    --emit-qir)
      EMIT_QIR=ON
      shift
      ;;
    --function)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --function is only valid for Python input." >&2
        exit 1
      fi
      FUNCTION_NAME="$2"
      shift 2
      ;;
    --stage)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --stage is only valid for Python input." >&2
        exit 1
      fi
      STAGE="$2"
      shift 2
      ;;

    --resolver)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --resolver is only valid for Python input." >&2
        exit 1
      fi
      RESOLVER="$2"
      shift 2
      ;;

      --passes=*)
        PASSES="${1#--passes=}"
        break
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# TODO: Following code needs improvement
if [[ -z "$INPUT_FILE" ]]; then
echo "No valid input file found!"
exit 1
fi

# TODO: Code to display helper options
# for arg in "${OTHER_ARGS[@]}"; do
#     if [[ "$arg" == -h ]]; then
#         {
#             "${MQSS_CUDAQ_OPT}" -h
#             "${MQSS_CATALYST_OPT}" -h
#         } | awk '!seen[$0]++'
#     fi
# done

# Split passes at commas
PASS_ARGS=()
IFS=',' read -ra PASS_LIST <<< "$PASSES"

for p in "${PASS_LIST[@]}"; do
    PASS_ARGS+=(--"$p")
done

filename=$(basename "$INPUT_FILE")
# Dispatch to correct optimizer
if [[ "${EXT}" == "cpp" ]]; then
    blank
    info "Converting the input to MLIR and applying specified optimization passes.."
    GENERATED_MLIR="${filename%.*}.qke"
    
    if [[ "${OUT_DIR}" != "" ]]; then
      cudaq-quake "${INPUT_FILE}" -o "${OUT_DIR}/${GENERATED_MLIR}"
      mqss-cudaq-opt "${OUT_DIR}/${GENERATED_MLIR}" "${PASS_ARGS[@]}" -o "${OUT_DIR}/${GENERATED_MLIR}"

      if [[ "${EMIT_QIR}" == "ON" ]]; then
        info "Emitting QIR..."
        echo " "
        cudaq-translate --convert-to=qir-full "${OUT_DIR}/${GENERATED_MLIR}" -o "${OUT_DIR}/${filename%.*}.ll"
      fi
      
    else

      if [[ "${EMIT_QIR}" == "ON" ]]; then
        info "Emitting QIR..."
        echo " "
        cudaq-quake "${INPUT_FILE}" | mqss-cudaq-opt "${PASS_ARGS[@]}" | cudaq-opt --quake-to-qir
      else
        cudaq-quake "${INPUT_FILE}" | mqss-cudaq-opt "${PASS_ARGS[@]}"
      fi
    fi
    
    # TODO: Further convert to QIR?

elif [[ "${EXT}" == "py" ]]; then
    blank
    msg "Python job details..."
    info "Function name: ${FUNCTION_NAME}"
    info "Stage: ${STAGE}"
    info "Resolver file: ${RESOLVER}"
    info "Passes: ${PASSES}"
    info "Out Dir: ${OUT_DIR}"

    if python3.11 -c "import catalyst"; then
     info "Catalyst python package found in current env"
    else
      warn "Catalyst python package not found"
      warn "Please enable the python virtual environment: source  MQSS-Passes-Suite/build/_deps/venv/bin/activate"
      exit 1
    fi

    COMMAND=""
    
    if [[ "${OUT_DIR}" != "" ]]; then
      COMMAND="$(
      python3.11 "${RESOLVER}" \
        --input "${INPUT_FILE}" \
        --function "${FUNCTION_NAME}" \
        --stage "${STAGE}" \
        --out-dir "${OUT_DIR}"
      )"
      MLIR_FILE="${OUT_DIR}/${FUNCTION_NAME}-${STAGE}.mlir"
      if [[ -e "${MLIR_FILE}" ]]; then
        info "MLIR Extracted: ${MLIR_FILE}"
      else
        warn "MLIR dialect could not be extracted"
        exit 1
      fi
      if [[ "${EMIT_QIR}" == "ON" ]]; then
        mqss-catalyst-opt "${MLIR_FILE}" "${PASS_ARGS[@]}" -o "${MLIR_FILE}"
        info "Emitting QIR..."
        echo " "
        catalyst --tool=all "${MLIR_FILE}" > "${OUT_DIR}/${filename%.*}.ll"
      else 
        mqss-catalyst-opt "${MLIR_FILE}" "${PASS_ARGS[@]}" -o "${MLIR_FILE}"
      fi
      

    else
      if [[ "${EMIT_QIR}" == "ON" ]]; then
        info "Emitting QIR..."
        echo " "
       python3.11 "${RESOLVER}" \
          --input "${INPUT_FILE}" \
          --function "${FUNCTION_NAME}" \
          --stage "${STAGE}" |  mqss-catalyst-opt "${PASS_ARGS[@]}" | catalyst --tool=all
      else
        python3.11 "${RESOLVER}" \
          --input "${INPUT_FILE}" \
          --function "${FUNCTION_NAME}" \
          --stage "${STAGE}" |  mqss-catalyst-opt "${PASS_ARGS[@]}"
      fi
    fi

    # TODO: Further convert to QIR? Use the following command
    
else
    warn "Unknown input type: $INPUT_FILE"
    exit 1
fi