#!/usr/bin/env bash

# Simple driver for selecting the correct optimizer

INPUT_FILE=""

INPUT_FILE=""
PASSES=""
OTHER_ARGS=()

# Parse arguments
for arg in "$@"; do
    case "$arg" in
        *.qke|*.quantum)
            INPUT_FILE="$arg"
            OTHER_ARGS+=("$arg")
            ;;
        --passes=*)
            PASSES="${arg#--passes=}"
            ;;
        *)
            OTHER_ARGS+=("$arg")
            ;;
    esac
done

if [[ -z "$INPUT_FILE" ]]; then
    echo "Error: No .quake or .quantum input file provided"
    exit 1
fi

# Split passes at commas
PASS_ARGS=()
IFS=',' read -ra PASS_LIST <<< "$PASSES"

echo "Passes:"
echo $PASSES

for p in "${PASS_LIST[@]}"; do
    PASS_ARGS+=(--"$p")
done



MQSS_CUDAQ_OPT="/workspaces/MQSS-Passes-Suite/build/tools/mqss-cudaq/bin/mqss-cudaq-opt"
MQSS_CATALYST_OPT="/workspaces/MQSS-Passes-Suite/build/tools/mqss-catalyst/bin/mqss-catalyst-opt"

# Dispatch to correct optimizer
if [[ "$INPUT_FILE" == *.qke ]]; then
    exec "${MQSS_CUDAQ_OPT}" "${OTHER_ARGS[@]}" "${PASS_ARGS[@]}"
elif [[ "$INPUT_FILE" == *.quantum ]]; then
    exec "${MQSS_CATALYST_OPT}" "${OTHER_ARGS[@]}" "${PASS_ARGS[@]}"
else
    echo "Unknown input type: $INPUT_FILE"
    exit 1
fi