#!/usr/bin/env bash

# Simple driver for selecting the correct optimizer


usage() {
  cat <<'EOF'
Usage:
  ./mqss-cc <input.{cpp|py}> [options] --passes=<pass-name>=mode=<mode>

options:
  Common:
    --out-dir DIR

  Python-only:
    --function NAME
    --stage NAME
    --resolver PATH

  Example Usage:
  1. For cudaq-quake
      ./mqss-cc test.cpp --out-dir output/ --passes=CommonGateCancellationPass=mode=CancelGate

  2. For catalyst-quantum
      ./mqss-cc test.py --function circuit --stage QuantumCompilationStage --out-dir output/ --passes=CommonGateCancellationPass=mode=CancelGate
EOF
}

INPUT_FILE=""

PASSES=""
OTHER_ARGS=()

# The following paths should be set on the command-line
export CUDA_QUAKE="/workspaces/executables/cudaq/bin/cudaq-quake"
MQSS_CUDAQ_OPT="/workspaces/MQSS-Passes-Suite/build/tools/mqss-cudaq/bin/mqss-cudaq-opt"
MQSS_CATALYST_OPT="/workspaces/MQSS-Passes-Suite/build/tools/mqss-catalyst/bin/mqss-catalyst-opt"

for p in "$MQSS_CUDAQ_OPT" "$MQSS_CATALYST_OPT"; do
  [[ -e "$p" ]] || { echo "Missing: $p, please check the build"; exit 1; }
done

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

INPUT_FILE="$1"
shift

if [[ ! -f "${INPUT_FILE}" ]]; then
  echo "Error: input file not found: ${INPUT_FILE}" >&2
  exit 1
fi

EXT="${INPUT_FILE##*.}"
FUNCTION_NAME=""
RESOLVER="/workspaces/MQSS-Passes-Suite/tools/resolve_python_input.py"
STAGE="QuantumCompilationStage"
OUT_DIR=""
TOOL_ARGS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-dir)
      OUT_DIR="$2"
      shift 2
      ;;

    --function)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --function is only valid for Python input." >&2
        exit 1
      fi
      FUNCTION_NAME="$2"
      shift 2
      ;;

    --stage)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --stage is only valid for Python input." >&2
        exit 1
      fi
      STAGE="$2"
      shift 2
      ;;

    --resolver)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --resolver is only valid for Python input." >&2
        exit 1
      fi
      RESOLVER="$2"
      shift 2
      ;;

      --passes=*)
        PASSES="${1#--passes=}"
        break
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# TODO: Following code needs improvement
if [[ -z "$INPUT_FILE" ]]; then
echo "No valid input file found!"
exit 1
fi

# TODO: Code to display helper options
# for arg in "${OTHER_ARGS[@]}"; do
#     if [[ "$arg" == -h ]]; then
#         {
#             "${MQSS_CUDAQ_OPT}" -h
#             "${MQSS_CATALYST_OPT}" -h
#         } | awk '!seen[$0]++'
#     fi
# done

# Split passes at commas
PASS_ARGS=()
IFS=',' read -ra PASS_LIST <<< "$PASSES"

for p in "${PASS_LIST[@]}"; do
    PASS_ARGS+=(--"$p")
done


# Dispatch to correct optimizer
if [[ "${EXT}" == "cpp" ]]; then
    echo " "
    echo "Converting the input to MLIR and applying specified optimization passes.."
    filename=$(basename "$INPUT_FILE")
    GENERATED_MLIR="${filename%.*}.qke"
    "${CUDA_QUAKE}" "${INPUT_FILE}" -o "${GENERATED_MLIR}"
    "${MQSS_CUDAQ_OPT}" "${GENERATED_MLIR}" "${PASS_ARGS[@]}" -o "${OUT_DIR}/${GENERATED_MLIR}"
    # TODO: Further convert to QIR?

elif [[ "${EXT}" == "py" ]]; then
    echo "Emitting arguments for now..."
    echo " "
    echo "Function name: ${FUNCTION_NAME}"
    echo "Stage: ${STAGE}"
    echo "Resolver file: ${RESOLVER}"
    echo "Passes: ${PASSES}"
    echo "Out Dir: ${OUT_DIR}"
    echo " "
    echo "Resolving the python input to extract MLIR..."
    COMMAND="$(
    python3 "${RESOLVER}" \
      --input "${INPUT_FILE}" \
      --function "${FUNCTION_NAME}" \
      --stage "${STAGE}" \
      --out-dir "${OUT_DIR}"
    )"

    MLIR_FILE="${OUT_DIR}/${FUNCTION_NAME}-${STAGE}.mlir"
    echo "${MLIR_FILE}"

    "${MQSS_CATALYST_OPT}" "${MLIR_FILE}" "${PASS_ARGS[@]}" -o "${MLIR_FILE}"
    # TODO: Further convert to QIR?
else
    echo "Unknown input type: $INPUT_FILE"
    exit 1
fi