#!/usr/bin/env bash

# Simple driver for selecting the correct optimizer


usage() {
  cat <<'EOF'
Usage:
  mytool.sh <input.{cpp|py}> [options] [-- <tool args>]

Common:
  --out-dir DIR

Python-only:
  --function NAME
  --stage NAME
  --resolver PATH

Examples:
  mytool.sh test.cpp --out-dir build
  mytool.sh test.py --function circuit --stage mlir_opt --out-dir build
EOF
}

INPUT_FILE=""

PASSES=""
OTHER_ARGS=()

# The following paths should be set on the command-line
export CUDA_QUAKE="/workspaces/executables/cudaq/bin/cudaq-quake"
MQSS_CUDAQ_OPT="/workspaces/MQSS-Passes-Suite/build/tools/mqss-cudaq/bin/mqss-cudaq-opt"
MQSS_CATALYST_OPT="/workspaces/MQSS-Passes-Suite/build/tools/mqss-catalyst/bin/mqss-catalyst-opt"


if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

INPUT_FILE="$1"
shift

if [[ ! -f "${INPUT_FILE}" ]]; then
  echo "Error: input file not found: ${INPUT_FILE}" >&2
  exit 1
fi

EXT="${INPUT_FILE##*.}"
FUNCTION_NAME=""
RESOLVER="workspaces/MQSS-Passes-Suite/tools/resolve_python_input.py"
STAGE="QuantumCompilationStage"
OUT_DIR=""
TOOL_ARGS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-dir)
      OUT_DIR="$2"
      shift 2
      ;;

    --function)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --function is only valid for Python input." >&2
        exit 1
      fi
      FUNCTION_NAME="$2"
      shift 2
      ;;

    --stage)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --stage is only valid for Python input." >&2
        exit 1
      fi
      STAGE="$2"
      shift 2
      ;;

    --resolver)
      if [[ "${EXT}" != "py" ]]; then
        echo "Error: --resolver is only valid for Python input." >&2
        exit 1
      fi
      RESOLVER="$2"
      shift 2
      ;;

      --passes=*)
        PASSES="${1#--passes=}"
        break
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# TODO: Following code needs improvement
if [[ -z "$INPUT_FILE" ]]; then
echo "No valid input file found!"
exit 1
fi

# TODO: Code to display helper options
# for arg in "${OTHER_ARGS[@]}"; do
#     if [[ "$arg" == -h ]]; then
#         {
#             "${MQSS_CUDAQ_OPT}" -h
#             "${MQSS_CATALYST_OPT}" -h
#         } | awk '!seen[$0]++'
#     fi
# done

# Split passes at commas
PASS_ARGS=()
IFS=',' read -ra PASS_LIST <<< "$PASSES"

for p in "${PASS_LIST[@]}"; do
    PASS_ARGS+=(--"$p")
done


# Dispatch to correct optimizer
if [[ "$INPUT_FILE" == *.cpp ]]; then
    echo " "
    echo "Converting the input to MLIR and applying specified optimization passes.."
    filename=$(basename "$INPUT_FILE")
    GENERATED_MLIR="${filename%.*}.qke"
    "${CUDA_QUAKE}" "${INPUT_FILE}" -o "${GENERATED_MLIR}"
    "${MQSS_CUDAQ_OPT}" "${GENERATED_MLIR}" "${PASS_ARGS[@]}" -o "${GENERATED_MLIR}"
    # TODO: Further convert to QIR?

elif [[ "$INPUT_FILE" == *.py ]]; then
    echo "Emitting arguments for now..."
    echo " "
    echo "Function name: ${FUNCTION_NAME}"
    echo "Stage: ${STAGE}"
    echo "Resolver file: ${RESOLVER}"
    echo "Passes: ${PASSES}"
    echo "Out Dir: ${OUT_DIR}"
    echo " "

    #"${MQSS_CATALYST_OPT}" "${GENERATED_MLIR}" "${PASS_ARGS[@]}" -o "${GENERATED_MLIR}"
    # TODO: Further convert to QIR?
else
    echo "Unknown input type: $INPUT_FILE"
    exit 1
fi