/* This code and any associated documentation is provided "as is"

Copyright 2024 Munich Quantum Software Stack Project

Licensed under the Apache License, Version 2.0 with LLVM Exceptions (the
"License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://github.com/Munich-Quantum-Software-Stack/passes/blob/develop/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.

SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
*************************************************************************
  author Martin Letras
  date   February 2025
  version 1.0
*************************************************************************/
/** @file
 * @brief
 * @details Header file that defines the signature for each MLIR/Quake defined
 * into the Munich Quantum Software Stack (MQSS).
 *
 * @par
 * This header must be included to use the collection of example passes that are
 * part of the MQSS.
 */

#ifndef EXAMPLES_H
#define EXAMPLES_H

#pragma once

#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassRegistry.h"

#include "llvm/Support/raw_ostream.h"

#include <stdexcept>

/**
 * @def CUDAQ_PREFIX_FUNCTION
 * @brief Macro defining the prefix of each quantum kernel generated by QUAKE
 * MLIR. This macro is used to identify MLIR/Quake quantum kernels.
 */
#define CUDAQ_PREFIX_FUNCTION "__nvqpp__mlirgen__"

namespace mqss_catalyst::opt {

/**
 * @brief Example custom MLIR pass.
   @details This method constructs an mlir::Pass of the type CustomExamplePass.
 This pass operates on any given MLIR/Quake module and replaces all Hadamard
 gates into a quantum circuit by S gates.

  \image html docs/_static/mqss-passes/CustomExamplePass.png width=60%

   @return An `mlir::Pass` object containing the definition of the
 CustomExamplePass. This `mlir::Pass` object has to be passed to an
 `mlir::PassManager` to transform any given MLIR module.
 */
std::unique_ptr<mlir::Pass> createCustomExamplePass();

/**
 * @brief Example MLIR pass that traverses a given MLIR/Quake.
   @details This method constructs an `mlir::Pass` of the type
 PrintQuakeGatesPas. This pass operates on any MLIR/Quake module and visit each
 operation dumping its name and type into the parameter `ostream`.
   @param[out] ostream A raw stream object that stores information about any
 given MLIR module.
   @return An `mlir::Pass` object containing the definition of the
 PrintQuakeGatesPas. This `mlir::Pass` object has to be passed to an
 `mlir::PassManager` to take effect on any given MLIR module.
 */
std::unique_ptr<mlir::Pass>
createPrintCatalystGatesPass(llvm::raw_ostream &ostream);
} // namespace mqss_catalyst::opt
#endif // EXAMPLES_H
