name: CI


on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout repo (gives us the Dockerfile)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          docker system prune -af

      # Step 2: Build Docker image using relative path
      - name: Build Docker image
        run: |
          docker build --build-arg CMAKE_ARCH=x86_64 \
           --progress=plain -t mqss-pass-dev -f .devcontainer/Dockerfile .

      - name: Build
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspaces/MQSS-Passes-Suite" \
            -v ${HOME}/.local/bin:/root/.local/bin \
            -w /workspaces/MQSS-Passes-Suite \
            mqss-pass-dev \
            bash -lc '
              make setup-env
              export PATH="${HOME}/.local/bin:$PATH"
              export PATH="/usr/local/bin:$PATH"
              make build
              make target
            '

      - name: Run Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspaces/MQSS-Passes-Suite \
            -v ${HOME}/.local/bin:/root/.local/bin \
            -w /workspaces/MQSS-Passes-Suite \
            mqss-pass-dev \
            bash -lc ' 
            export PATH="${HOME}/.local/bin:$PATH"
            export PATH="/usr/local/bin:$PATH"
            which mqss-opt
            make test-dialects '