name: CI

on:
  push:
    branches: [develop, catalyst-integration]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CUDAQ_BIN: /workspaces/MQSS-Passes-Suite/_deps/mqss-cudaq/cudaq/bin

    steps:
      # Step 1: Checkout repo (gives us the Dockerfile)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build Docker image using relative path
      - name: Build Docker image
        run: |
          docker build -t mqss-pass-dev -f .devcontainer/Dockerfile .

      - name: Build
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspaces/MQSS-Passes-Suite" \
            -w /workspaces/MQSS-Passes-Suite \
            mqss-pass-dev \
            bash -lc '
              make python
              source _deps/.venv/bin/activate
              which python
              python -c "import sys; print(sys.executable)"
              make build
              make target
            '

      - name: Run Tests
        run: |
          docker run --rm \
            -e PATH="/root/.local/bin:${{ env.CUDAQ_BIN }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
            -v ${{ github.workspace }}:/workspaces/MQSS-Passes-Suite \
            -w /workspaces/MQSS-Passes-Suite \
            mqss-pass-dev bash -lc "source /workspaces/MQSS-Passes-Suite/_deps/.venv/bin/activate && make test-all"