name: pre-commit

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Cache pre-commit environments
        uses: actions/cache@v6
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install uv pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
